// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-MLPyckIgRqgBQ4zPrg1wOXsf177Ko5c',
    appId: '1:231830430213:web:93bf1b1457c0a328bab26c',
    messagingSenderId: '231830430213',
    projectId: 'info-c1887',
    authDomain: 'info-c1887.firebaseapp.com',
    databaseURL: 'https://info-c1887-default-rtdb.firebaseio.com',
    storageBucket: 'info-c1887.appspot.com',
    measurementId: 'G-3XLS9DCM13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxBv6N3R4qxt-IEjk7WDxc284VPKxneVI',
    appId: '1:231830430213:android:f6c541bc44a0ebaebab26c',
    messagingSenderId: '231830430213',
    projectId: 'info-c1887',
    databaseURL: 'https://info-c1887-default-rtdb.firebaseio.com',
    storageBucket: 'info-c1887.appspot.com',
  );
}
